'use client';
import { useState, useEffect, useRef } from 'react';

const TOPICS = [
  { label: '🚚 TMS / Gestão de Transporte', value: 'TMS logistics management software for Brazilian companies' },
  { label: '📦 Rastreamento de Cargas', value: 'cargo tracking and visibility solutions for logistics' },
  { label: '💡 Inovação em Logística', value: 'innovation and digital transformation in logistics and supply chain' },
  { label: '📊 Redução de Custos', value: 'cost reduction and efficiency in transportation management' },
  { label: '🤝 Case de Sucesso', value: 'success story of a company that improved logistics with technology' },
  { label: '🔗 Integração de Sistemas', value: 'ERP and TMS integration for logistics automation' },
  { label: '🌎 Expansão Comercial', value: 'B2B commercial expansion and prospecting in logistics sector' },
];

const STYLES = [
  { label: 'Profissional', value: 'professional' },
  { label: 'Impactante', value: 'bold' },
  { label: 'Amigável', value: 'friendly' },
];

const PLATFORMS = [
  { label: 'LinkedIn', value: 'linkedin', color: '#0a66c2', icon: '💼' },
  { label: 'Instagram', value: 'instagram', color: '#e1306c', icon: '📸' },
];

export default function SocialPage() {
  const [platform, setPlatform] = useState('linkedin');
  const [topic, setTopic] = useState(TOPICS[0].value);
  const [style, setStyle] = useState('professional');
  const [customPrompt, setCustomPrompt] = useState('');
  const [caption, setCaption] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [uploadedImage, setUploadedImage] = useState('');
  const [generatingImage, setGeneratingImage] = useState(false);
  const [generatingCaption, setGeneratingCaption] = useState(false);
  const [generatingBoth, setGeneratingBoth] = useState(false);
  const [posting, setPosting] = useState(false);
  const [toast, setToast] = useState('');
  const [tab, setTab] = useState<'create' | 'schedule'>('create');
  const [copied, setCopied] = useState(false);
  const hasAutoGenerated = useRef(false);

  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(''), 4000);
  };

  // Gerar imagem + legenda automaticamente ao entrar na página
  useEffect(() => {
    if (!hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateBoth();
    }
  }, []);

  const generateImage = async (topicOverride?: string, platformOverride?: string) => {
    const t = topicOverride ?? topic;
    const p = platformOverride ?? platform;
    setGeneratingImage(true);
    setImageUrl('');
    setUploadedImage('');
    try {
      const res = await fetch('/api/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: t, style, platform: p, prompt: customPrompt || undefined }),
      });
      const data = await res.json();
      if (data.url) {
        setImageUrl(data.url);
      }
    } catch {}
    setGeneratingImage(false);
  };

  const generateCaption = async (topicOverride?: string, platformOverride?: string, styleOverride?: string) => {
    const t = topicOverride ?? topic;
    const p = platformOverride ?? platform;
    const s = styleOverride ?? style;
    setGeneratingCaption(true);
    try {
      const res = await fetch('/api/generate-social-post', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ platform: p, topic: t, style: s, customPrompt }),
      });
      const data = await res.json();
      if (data.caption) {
        setCaption(data.caption);
      }
    } catch {}
    setGeneratingCaption(false);
  };

  const generateBoth = async (topicOverride?: string, platformOverride?: string) => {
    const t = topicOverride ?? topic;
    const p = platformOverride ?? platform;
    setGeneratingBoth(true);
    setCaption('');
    setImageUrl('');
    setUploadedImage('');
    await Promise.all([
      generateImage(t, p),
      generateCaption(t, p),
    ]);
    setGeneratingBoth(false);
    showToast('✅ Post gerado com IA!');
  };

  const postToInstagram = async () => {
    if (!caption.trim()) { showToast('⚠️ Adicione uma legenda antes de publicar'); return; }
    const finalImage = uploadedImage || imageUrl;
    if (!finalImage) { showToast('⚠️ Adicione ou gere uma imagem antes de publicar'); return; }
    setPosting(true);
    try {
      const res = await fetch('/api/instagram', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ caption, imageUrl: finalImage }),
      });
      const data = await res.json();
      if (data.success || data.id) {
        showToast('✅ Post publicado no Instagram @get.tms!');
        setCaption(''); setImageUrl(''); setUploadedImage('');
      } else {
        showToast('❌ Erro: ' + (data.error || 'Falha ao publicar'));
      }
    } catch {
      showToast('❌ Erro ao publicar no Instagram');
    }
    setPosting(false);
  };

  const openLinkedIn = () => {
    const text = encodeURIComponent(caption);
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=https://gettms.com.br&summary=${text}`, '_blank');
    showToast('✅ LinkedIn aberto para publicação!');
  };

  const copyCaption = () => {
    navigator.clipboard.writeText(caption);
    setCopied(true);
    showToast('✅ Copiado!');
    setTimeout(() => setCopied(false), 2000);
  };

  const finalImage = uploadedImage || imageUrl;
  const isLoading = generatingBoth || generatingImage || generatingCaption;

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', fontFamily: 'Inter, -apple-system, sans-serif' }}>

      {/* Toast */}
      {toast && (
        <div style={{
          position: 'fixed', top: 20, right: 20, zIndex: 9999,
          background: '#0f172a', color: '#fff', borderRadius: 10,
          padding: '12px 20px', fontSize: 13, fontWeight: 500,
          boxShadow: '0 8px 24px rgba(0,0,0,0.25)',
          border: '1px solid rgba(255,255,255,0.08)',
          animation: 'slideIn 0.2s ease',
        }}>
          {toast}
        </div>
      )}

      <style>{`
        @keyframes slideIn { from { opacity: 0; transform: translateY(-8px); } to { opacity: 1; transform: translateY(0); } }
        @keyframes pulse { 0%, 100% { opacity: 1; } 50% { opacity: 0.4; } }
        @keyframes shimmer { 0% { background-position: -200% 0; } 100% { background-position: 200% 0; } }
        .skeleton {
          background: linear-gradient(90deg, var(--surface-2) 25%, var(--border) 50%, var(--surface-2) 75%);
          background-size: 200% 100%;
          animation: shimmer 1.5s infinite;
          border-radius: 6px;
        }
        .topic-btn:hover { background: var(--primary-soft) !important; border-color: var(--primary-border) !important; color: var(--primary) !important; }
        .style-btn:hover { opacity: 0.85; }
        .action-btn:hover { filter: brightness(1.08); transform: translateY(-1px); }
        .action-btn:active { transform: translateY(0); }
      `}</style>

      <div style={{ maxWidth: 1100, margin: '0 auto', padding: '24px 20px' }}>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 12 }}>
            <a href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: 'var(--text-muted)', textDecoration: 'none', fontSize: 13, padding: '6px 10px', borderRadius: 7, border: '1px solid var(--border)', background: 'var(--surface)', transition: 'all 0.12s' }}>
              ← CRM
            </a>
            <span style={{ color: 'var(--border-strong)' }}>/</span>
            <span style={{ fontWeight: 700, fontSize: 17, color: 'var(--text)' }}>📣 Social Media</span>
          </div>

          {/* Tabs */}
          <div style={{ display: 'flex', gap: 2, background: 'var(--surface)', borderRadius: 9, padding: 3, border: '1px solid var(--border)' }}>
            {[{ key: 'create', label: '✏️ Criar Post' }, { key: 'schedule', label: '📅 Agendados' }].map(t => (
              <button key={t.key} onClick={() => setTab(t.key as any)}
                style={{ background: tab === t.key ? 'var(--primary)' : 'transparent', color: tab === t.key ? '#fff' : 'var(--text-muted)', border: 'none', borderRadius: 7, padding: '7px 16px', cursor: 'pointer', fontWeight: tab === t.key ? 600 : 400, fontSize: 13, transition: 'all 0.15s', boxShadow: tab === t.key ? '0 1px 4px rgba(37,99,235,0.3)' : 'none' }}>
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {tab === 'create' && (
          <div style={{ display: 'grid', gridTemplateColumns: '340px 1fr', gap: 20, alignItems: 'start' }}>

            {/* ── Coluna esquerda: configurações ── */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 14 }}>

              {/* Plataforma */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 18, border: '1px solid var(--border)', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Plataforma</div>
                <div style={{ display: 'flex', gap: 8 }}>
                  {PLATFORMS.map(p => (
                    <button key={p.value} onClick={() => { setPlatform(p.value); }}
                      style={{ flex: 1, background: platform === p.value ? p.color : 'var(--surface-2)', color: platform === p.value ? '#fff' : 'var(--text-secondary)', border: `1px solid ${platform === p.value ? p.color : 'var(--border)'}`, borderRadius: 8, padding: '9px 0', cursor: 'pointer', fontWeight: 600, fontSize: 13, transition: 'all 0.15s', boxShadow: platform === p.value ? `0 2px 8px ${p.color}40` : 'none' }}>
                      {p.icon} {p.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Tema */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 18, border: '1px solid var(--border)', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Tema do Post</div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 5 }}>
                  {TOPICS.map(t => (
                    <button key={t.value} onClick={() => setTopic(t.value)} className="topic-btn"
                      style={{ background: topic === t.value ? 'var(--primary-soft)' : 'transparent', color: topic === t.value ? 'var(--primary)' : 'var(--text-secondary)', border: `1px solid ${topic === t.value ? 'var(--primary-border)' : 'transparent'}`, borderRadius: 7, padding: '7px 10px', cursor: 'pointer', fontSize: 13, textAlign: 'left', fontWeight: topic === t.value ? 600 : 400, transition: 'all 0.12s' }}>
                      {t.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Estilo */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 18, border: '1px solid var(--border)', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Tom do Post</div>
                <div style={{ display: 'flex', gap: 6 }}>
                  {STYLES.map(s => (
                    <button key={s.value} onClick={() => setStyle(s.value)} className="style-btn"
                      style={{ flex: 1, background: style === s.value ? 'var(--primary)' : 'var(--surface-2)', color: style === s.value ? '#fff' : 'var(--text-secondary)', border: `1px solid ${style === s.value ? 'var(--primary)' : 'var(--border)'}`, borderRadius: 7, padding: '7px 0', cursor: 'pointer', fontSize: 12, fontWeight: style === s.value ? 600 : 400, transition: 'all 0.15s', boxShadow: style === s.value ? '0 1px 4px rgba(37,99,235,0.25)' : 'none' }}>
                      {s.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Instrução adicional */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 18, border: '1px solid var(--border)', boxShadow: '0 1px 3px rgba(0,0,0,0.04)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 8 }}>Instrução Adicional (opcional)</div>
                <textarea
                  value={customPrompt}
                  onChange={e => setCustomPrompt(e.target.value)}
                  placeholder="Ex: Foque em distribuidoras de alimentos, mencione integração com TOTVS..."
                  rows={3}
                  style={{ width: '100%', border: '1px solid var(--border-strong)', borderRadius: 8, padding: '8px 10px', fontSize: 12, resize: 'none', boxSizing: 'border-box', fontFamily: 'inherit', color: 'var(--text)', background: 'var(--surface)', outline: 'none', lineHeight: 1.5 }}
                />
              </div>

              {/* Botão principal: Gerar tudo com IA */}
              <button
                onClick={() => generateBoth()}
                disabled={isLoading}
                style={{ width: '100%', background: isLoading ? 'var(--text-muted)' : 'linear-gradient(135deg, #2563eb, #7c3aed)', color: '#fff', border: 'none', borderRadius: 10, padding: '13px 0', cursor: isLoading ? 'not-allowed' : 'pointer', fontWeight: 700, fontSize: 14, transition: 'all 0.2s', boxShadow: isLoading ? 'none' : '0 4px 14px rgba(37,99,235,0.35)', letterSpacing: '0.01em' }}
                className="action-btn"
              >
                {isLoading ? '⏳ Gerando post com IA...' : '✨ Gerar Post Completo com IA'}
              </button>
            </div>

            {/* ── Coluna direita: preview grande ── */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

              {/* Preview de imagem — GRANDE */}
              <div style={{ background: 'var(--surface)', borderRadius: 14, overflow: 'hidden', border: '1px solid var(--border)', boxShadow: '0 2px 8px rgba(0,0,0,0.06)' }}>
                {/* Barra de plataforma */}
                <div style={{ padding: '12px 18px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--surface-2)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <div style={{ width: 28, height: 28, borderRadius: 6, background: platform === 'linkedin' ? '#0a66c2' : 'linear-gradient(135deg, #e1306c, #833ab4)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14 }}>
                      {platform === 'linkedin' ? '💼' : '📸'}
                    </div>
                    <span style={{ fontWeight: 600, fontSize: 13, color: 'var(--text)' }}>
                      {platform === 'linkedin' ? 'LinkedIn Preview' : 'Instagram Preview'}
                    </span>
                  </div>
                  <div style={{ display: 'flex', gap: 6 }}>
                    <button onClick={() => generateImage()} disabled={generatingImage}
                      style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 7, padding: '5px 12px', fontSize: 12, fontWeight: 500, cursor: generatingImage ? 'not-allowed' : 'pointer', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: 5 }}>
                      {generatingImage ? '⏳' : '🔄'} Nova imagem
                    </button>
                    <label style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 7, padding: '5px 12px', fontSize: 12, fontWeight: 500, cursor: 'pointer', color: 'var(--text-secondary)', display: 'flex', alignItems: 'center', gap: 5 }}>
                      📁 Upload
                      <input type="file" accept="image/*" style={{ display: 'none' }} onChange={e => {
                        const file = e.target.files?.[0];
                        if (file) {
                          const reader = new FileReader();
                          reader.onload = ev => setUploadedImage(ev.target?.result as string);
                          reader.readAsDataURL(file);
                        }
                      }} />
                    </label>
                    {finalImage && (
                      <button onClick={() => { setImageUrl(''); setUploadedImage(''); }}
                        style={{ background: 'var(--danger-soft)', border: '1px solid #fecaca', borderRadius: 7, padding: '5px 10px', fontSize: 12, cursor: 'pointer', color: 'var(--danger)' }}>
                        🗑️
                      </button>
                    )}
                  </div>
                </div>

                {/* Imagem grande */}
                <div style={{
                  width: '100%',
                  aspectRatio: platform === 'linkedin' ? '16/9' : '4/3',
                  background: 'var(--surface-2)',
                  overflow: 'hidden',
                  position: 'relative',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                }}>
                  {generatingImage ? (
                    <div className="skeleton" style={{ position: 'absolute', inset: 0 }}>
                      <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 10 }}>
                        <div style={{ fontSize: 32, animation: 'pulse 1.5s infinite' }}>🤖</div>
                        <div style={{ fontSize: 13, color: 'var(--text-muted)', fontWeight: 500 }}>Buscando imagem...</div>
                      </div>
                    </div>
                  ) : finalImage ? (
                    <img src={finalImage} alt="Post preview" style={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                  ) : (
                    <div style={{ textAlign: 'center', color: 'var(--text-muted)', padding: 32 }}>
                      <div style={{ fontSize: 48, marginBottom: 10 }}>🖼️</div>
                      <div style={{ fontSize: 14, fontWeight: 500, marginBottom: 4 }}>Nenhuma imagem ainda</div>
                      <div style={{ fontSize: 12 }}>Clique em "Gerar Post Completo com IA" para começar</div>
                    </div>
                  )}
                </div>
              </div>

              {/* Legenda gerada */}
              <div style={{ background: 'var(--surface)', borderRadius: 14, border: '1px solid var(--border)', boxShadow: '0 2px 8px rgba(0,0,0,0.06)', overflow: 'hidden' }}>
                <div style={{ padding: '14px 18px', borderBottom: '1px solid var(--border)', background: 'var(--surface-2)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ fontWeight: 600, fontSize: 13, color: 'var(--text)' }}>📝 Legenda do Post</span>
                  <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                    <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{caption.length} caracteres</span>
                    <button onClick={() => generateCaption()} disabled={generatingCaption}
                      style={{ background: 'var(--primary-soft)', border: '1px solid var(--primary-border)', borderRadius: 6, padding: '4px 11px', fontSize: 12, fontWeight: 600, cursor: generatingCaption ? 'not-allowed' : 'pointer', color: 'var(--primary)', display: 'flex', alignItems: 'center', gap: 5 }}>
                      {generatingCaption ? '⏳' : '🤖'} Regerar
                    </button>
                  </div>
                </div>

                <div style={{ padding: '16px 18px' }}>
                  {generatingCaption ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                      {[100, 85, 90, 70, 95, 60].map((w, i) => (
                        <div key={i} className="skeleton" style={{ height: 14, width: `${w}%` }} />
                      ))}
                    </div>
                  ) : (
                    <textarea
                      value={caption}
                      onChange={e => setCaption(e.target.value)}
                      placeholder="Clique em 'Gerar Post Completo com IA' para criar um post profissional pronto para publicar..."
                      rows={10}
                      style={{ width: '100%', border: 'none', borderRadius: 0, padding: 0, fontSize: 13, resize: 'none', boxSizing: 'border-box', fontFamily: 'inherit', color: 'var(--text)', background: 'transparent', outline: 'none', lineHeight: 1.7 }}
                    />
                  )}
                </div>
              </div>

              {/* Ações de publicação */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
                <button onClick={openLinkedIn} disabled={!caption.trim()} className="action-btn"
                  style={{ background: '#0a66c2', color: '#fff', border: 'none', borderRadius: 10, padding: '13px 0', cursor: caption.trim() ? 'pointer' : 'not-allowed', fontWeight: 700, fontSize: 13, opacity: caption.trim() ? 1 : 0.5, transition: 'all 0.15s', boxShadow: caption.trim() ? '0 3px 10px rgba(10,102,194,0.35)' : 'none' }}>
                  💼 LinkedIn
                </button>
                <button onClick={postToInstagram} disabled={posting || !caption.trim()} className="action-btn"
                  style={{ background: 'linear-gradient(135deg, #e1306c, #833ab4)', color: '#fff', border: 'none', borderRadius: 10, padding: '13px 0', cursor: (posting || !caption.trim()) ? 'not-allowed' : 'pointer', fontWeight: 700, fontSize: 13, opacity: (posting || !caption.trim()) ? 0.5 : 1, transition: 'all 0.15s', boxShadow: (!posting && caption.trim()) ? '0 3px 10px rgba(225,48,108,0.35)' : 'none' }}>
                  {posting ? '⏳...' : '📸 Instagram'}
                </button>
                <button onClick={copyCaption} disabled={!caption.trim()} className="action-btn"
                  style={{ background: copied ? 'var(--success-soft)' : 'var(--surface)', color: copied ? 'var(--success)' : 'var(--text-secondary)', border: `1px solid ${copied ? '#a7f3d0' : 'var(--border)'}`, borderRadius: 10, padding: '13px 0', cursor: caption.trim() ? 'pointer' : 'not-allowed', fontWeight: 600, fontSize: 13, opacity: caption.trim() ? 1 : 0.5, transition: 'all 0.15s' }}>
                  {copied ? '✅ Copiado!' : '📋 Copiar'}
                </button>
              </div>
            </div>
          </div>
        )}

        {tab === 'schedule' && (
          <div style={{ background: 'var(--surface)', borderRadius: 14, padding: 60, border: '1px solid var(--border)', textAlign: 'center', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: 48, marginBottom: 14 }}>📅</div>
            <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 8, color: 'var(--text)' }}>Agendamento de Posts</div>
            <div style={{ fontSize: 14, color: 'var(--text-secondary)' }}>Em breve: agende posts para LinkedIn e Instagram com antecedência.</div>
          </div>
        )}
      </div>
    </div>
  );
}
