'use client';
import { useState, useEffect, useRef, useCallback } from 'react';

const TOPICS = [
  { label: '🚚 TMS / Gestão de Transporte', value: 'TMS logistics management software for Brazilian companies', short: 'TMS & Gestão de Transporte' },
  { label: '📦 Rastreamento de Cargas', value: 'cargo tracking and visibility solutions for logistics', short: 'Rastreamento de Cargas' },
  { label: '💡 Inovação em Logística', value: 'innovation and digital transformation in logistics and supply chain', short: 'Inovação em Logística' },
  { label: '📊 Redução de Custos', value: 'cost reduction and efficiency in transportation management', short: 'Redução de Custos' },
  { label: '🤝 Case de Sucesso', value: 'success story of a company that improved logistics with technology', short: 'Case de Sucesso' },
  { label: '🔗 Integração de Sistemas', value: 'ERP and TMS integration for logistics automation', short: 'Integração de Sistemas' },
  { label: '🌎 Expansão Comercial', value: 'B2B commercial expansion and prospecting in logistics sector', short: 'Expansão Comercial' },
];

const STYLES = [
  { label: 'Profissional', value: 'professional' },
  { label: 'Impactante', value: 'bold' },
  { label: 'Amigável', value: 'friendly' },
];

const PLATFORMS = [
  { label: 'LinkedIn', value: 'linkedin', color: '#0a66c2', icon: '💼' },
  { label: 'Instagram', value: 'instagram', color: '#e1306c', icon: '📸' },
];

// Extrai o gancho (primeira linha) da legenda
function extractHook(text: string): string {
  const lines = text.split('\n').filter(l => l.trim().length > 0);
  return lines[0]?.replace(/^[#*_]+/, '').trim() || '';
}

// Quebra texto em linhas para o canvas
function wrapText(ctx: CanvasRenderingContext2D, text: string, maxWidth: number): string[] {
  const words = text.split(' ');
  const lines: string[] = [];
  let current = '';
  for (const word of words) {
    const test = current ? `${current} ${word}` : word;
    if (ctx.measureText(test).width > maxWidth && current) {
      lines.push(current);
      current = word;
    } else {
      current = test;
    }
  }
  if (current) lines.push(current);
  return lines;
}

export default function SocialPage() {
  const [platform, setPlatform] = useState('linkedin');
  const [topic, setTopic] = useState(TOPICS[0].value);
  const [style, setStyle] = useState('professional');
  const [customPrompt, setCustomPrompt] = useState('');
  const [caption, setCaption] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [uploadedImage, setUploadedImage] = useState('');
  const [generatingImage, setGeneratingImage] = useState(false);
  const [generatingCaption, setGeneratingCaption] = useState(false);
  const [generatingBoth, setGeneratingBoth] = useState(false);
  const [posting, setPosting] = useState(false);
  const [toast, setToast] = useState('');
  const [tab, setTab] = useState<'create' | 'schedule'>('create');
  const [copied, setCopied] = useState(false);
  const [folderReady, setFolderReady] = useState(false);
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const hasAutoGenerated = useRef(false);

  const showToast = (msg: string) => {
    setToast(msg);
    setTimeout(() => setToast(''), 4000);
  };

  // Renderiza o folder no canvas
  const renderFolder = useCallback(async (imgSrc: string, captionText: string, plt: string) => {
    const canvas = canvasRef.current;
    if (!canvas || !imgSrc || !captionText) return;

    const isInstagram = plt === 'instagram';
    const W = isInstagram ? 1080 : 1200;
    const H = isInstagram ? 1080 : 628;
    canvas.width = W;
    canvas.height = H;
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    setFolderReady(false);

    // Carregar imagem de fundo
    const img = new Image();
    img.crossOrigin = 'anonymous';
    img.src = imgSrc;
    await new Promise<void>((resolve, reject) => {
      img.onload = () => resolve();
      img.onerror = () => reject();
    }).catch(() => {});

    // Desenhar imagem de fundo
    ctx.drawImage(img, 0, 0, W, H);

    // Overlay gradiente escuro na parte inferior (2/3 da altura)
    const grad = ctx.createLinearGradient(0, H * 0.25, 0, H);
    grad.addColorStop(0, 'rgba(0,0,0,0)');
    grad.addColorStop(0.45, 'rgba(0,10,30,0.72)');
    grad.addColorStop(1, 'rgba(0,5,20,0.95)');
    ctx.fillStyle = grad;
    ctx.fillRect(0, 0, W, H);

    // Barra de cor no topo (accent)
    const accentColor = plt === 'linkedin' ? '#0a66c2' : '#e1306c';
    ctx.fillStyle = accentColor;
    ctx.fillRect(0, 0, W, 6);

    // ── Logo / marca no topo esquerdo ──
    const pad = isInstagram ? 48 : 40;
    ctx.font = `bold ${isInstagram ? 28 : 22}px Inter, Arial, sans-serif`;
    ctx.fillStyle = '#ffffff';
    ctx.globalAlpha = 0.95;
    ctx.fillText('getLOG', pad, isInstagram ? 80 : 60);
    ctx.font = `${isInstagram ? 16 : 13}px Inter, Arial, sans-serif`;
    ctx.fillStyle = accentColor;
    ctx.fillText('by Lottustech', pad, isInstagram ? 105 : 80);
    ctx.globalAlpha = 1;

    // ── Tag de tema no topo direito ──
    const topicShort = TOPICS.find(t => t.value === topic)?.short || 'Logística';
    const tagText = topicShort.replace(/^[^\w]*/, '');
    ctx.font = `600 ${isInstagram ? 18 : 14}px Inter, Arial, sans-serif`;
    const tagW = ctx.measureText(tagText).width + (isInstagram ? 32 : 24);
    const tagH = isInstagram ? 36 : 28;
    const tagX = W - tagW - pad;
    const tagY = isInstagram ? 58 : 44;
    // Fundo da tag
    ctx.fillStyle = 'rgba(255,255,255,0.12)';
    ctx.beginPath();
    ctx.roundRect(tagX, tagY, tagW, tagH, 8);
    ctx.fill();
    ctx.strokeStyle = 'rgba(255,255,255,0.25)';
    ctx.lineWidth = 1;
    ctx.stroke();
    ctx.fillStyle = '#ffffff';
    ctx.fillText(tagText, tagX + (isInstagram ? 16 : 12), tagY + tagH - (isInstagram ? 10 : 8));

    // ── Gancho principal (headline) ──
    const hook = extractHook(captionText);
    const hookFontSize = isInstagram ? 52 : 40;
    ctx.font = `bold ${hookFontSize}px Inter, Arial, sans-serif`;
    ctx.fillStyle = '#ffffff';
    const maxW = W - pad * 2;
    const hookLines = wrapText(ctx, hook, maxW);
    const hookLineH = hookFontSize * 1.2;
    const totalHookH = hookLines.length * hookLineH;
    const hookY = H - (isInstagram ? 260 : 200) - totalHookH;

    hookLines.forEach((line, i) => {
      ctx.fillText(line, pad, hookY + i * hookLineH);
    });

    // ── Linha divisória ──
    ctx.fillStyle = accentColor;
    ctx.fillRect(pad, hookY + totalHookH + (isInstagram ? 16 : 12), isInstagram ? 80 : 60, isInstagram ? 4 : 3);

    // ── Subtítulo / segunda linha da legenda ──
    const lines2 = captionText.split('\n').filter(l => l.trim().length > 0);
    const subtitle = lines2[1]?.replace(/^[#*_\-•]+\s*/, '').trim() || 'getLOG/Lottustech — TMS para distribuidoras';
    ctx.font = `${isInstagram ? 24 : 18}px Inter, Arial, sans-serif`;
    ctx.fillStyle = 'rgba(255,255,255,0.80)';
    const subLines = wrapText(ctx, subtitle, maxW);
    const subY = hookY + totalHookH + (isInstagram ? 36 : 26);
    subLines.slice(0, 2).forEach((line, i) => {
      ctx.fillText(line, pad, subY + i * (isInstagram ? 32 : 24));
    });

    // ── Rodapé: CTA + site ──
    const footerY = H - (isInstagram ? 56 : 44);
    ctx.font = `600 ${isInstagram ? 20 : 15}px Inter, Arial, sans-serif`;
    ctx.fillStyle = 'rgba(255,255,255,0.55)';
    ctx.fillText('gettms.com.br  ·  linkedin.com/company/lottustech', pad, footerY);

    // ── Ícone de plataforma ──
    ctx.font = `bold ${isInstagram ? 22 : 17}px Inter, Arial, sans-serif`;
    ctx.fillStyle = accentColor;
    const platLabel = plt === 'linkedin' ? '💼 LinkedIn' : '📸 Instagram';
    const platW = ctx.measureText(platLabel).width;
    ctx.fillText(platLabel, W - platW - pad, footerY);

    setFolderReady(true);
  }, [topic]);

  // Re-renderizar folder quando imagem ou legenda mudar
  useEffect(() => {
    const img = uploadedImage || imageUrl;
    if (img && caption) {
      renderFolder(img, caption, platform);
    }
  }, [imageUrl, uploadedImage, caption, platform, renderFolder]);

  // Gerar imagem + legenda automaticamente ao entrar na página
  useEffect(() => {
    if (!hasAutoGenerated.current) {
      hasAutoGenerated.current = true;
      generateBoth();
    }
  }, []);

  const generateImage = async (topicOverride?: string, platformOverride?: string) => {
    const t = topicOverride ?? topic;
    const p = platformOverride ?? platform;
    setGeneratingImage(true);
    setImageUrl('');
    setUploadedImage('');
    setFolderReady(false);
    try {
      const res = await fetch('/api/generate-image', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ topic: t, style, platform: p }),
      });
      const data = await res.json();
      if (data.url) setImageUrl(data.url);
    } catch {}
    setGeneratingImage(false);
  };

  const generateCaption = async (topicOverride?: string, platformOverride?: string, styleOverride?: string) => {
    const t = topicOverride ?? topic;
    const p = platformOverride ?? platform;
    const s = styleOverride ?? style;
    setGeneratingCaption(true);
    try {
      const res = await fetch('/api/generate-social-post', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ platform: p, topic: t, style: s, customPrompt }),
      });
      const data = await res.json();
      if (data.caption) setCaption(data.caption);
    } catch {}
    setGeneratingCaption(false);
  };

  const generateBoth = async (topicOverride?: string, platformOverride?: string) => {
    const t = topicOverride ?? topic;
    const p = platformOverride ?? platform;
    setGeneratingBoth(true);
    setCaption('');
    setImageUrl('');
    setUploadedImage('');
    setFolderReady(false);
    await Promise.all([generateImage(t, p), generateCaption(t, p)]);
    setGeneratingBoth(false);
    showToast('✅ Folder gerado com IA!');
  };

  const downloadFolder = () => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const link = document.createElement('a');
    link.download = `post-${platform}-${Date.now()}.png`;
    link.href = canvas.toDataURL('image/png');
    link.click();
    showToast('✅ Folder baixado!');
  };

  const postToInstagram = async () => {
    if (!caption.trim()) { showToast('⚠️ Adicione uma legenda antes de publicar'); return; }
    const finalImage = uploadedImage || imageUrl;
    if (!finalImage) { showToast('⚠️ Adicione ou gere uma imagem antes de publicar'); return; }
    setPosting(true);
    try {
      const res = await fetch('/api/instagram', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ caption, imageUrl: finalImage }),
      });
      const data = await res.json();
      if (data.success || data.id) {
        showToast('✅ Post publicado no Instagram @get.tms!');
        setCaption(''); setImageUrl(''); setUploadedImage(''); setFolderReady(false);
      } else {
        showToast('❌ Erro: ' + (data.error || 'Falha ao publicar'));
      }
    } catch { showToast('❌ Erro ao publicar no Instagram'); }
    setPosting(false);
  };

  const openLinkedIn = () => {
    window.open(`https://www.linkedin.com/sharing/share-offsite/?url=https://gettms.com.br&summary=${encodeURIComponent(caption)}`, '_blank');
    showToast('✅ LinkedIn aberto!');
  };

  const copyCaption = () => {
    navigator.clipboard.writeText(caption);
    setCopied(true);
    showToast('✅ Copiado!');
    setTimeout(() => setCopied(false), 2000);
  };

  const isLoading = generatingBoth || generatingImage || generatingCaption;
  const finalImage = uploadedImage || imageUrl;

  return (
    <div style={{ minHeight: '100vh', background: 'var(--bg)', fontFamily: 'Inter, -apple-system, sans-serif' }}>
      {toast && (
        <div style={{ position: 'fixed', top: 20, right: 20, zIndex: 9999, background: '#0f172a', color: '#fff', borderRadius: 10, padding: '12px 20px', fontSize: 13, fontWeight: 500, boxShadow: '0 8px 24px rgba(0,0,0,0.25)', border: '1px solid rgba(255,255,255,0.08)' }}>
          {toast}
        </div>
      )}

      <style>{`
        @keyframes pulse { 0%,100%{opacity:1}50%{opacity:.4} }
        @keyframes shimmer { 0%{background-position:-200% 0}100%{background-position:200% 0} }
        .skeleton { background: linear-gradient(90deg,var(--surface-2) 25%,var(--border) 50%,var(--surface-2) 75%); background-size:200% 100%; animation:shimmer 1.5s infinite; border-radius:6px; }
        .topic-btn:hover { background:var(--primary-soft)!important; border-color:var(--primary-border)!important; color:var(--primary)!important; }
        .act-btn { transition: all 0.15s; }
        .act-btn:hover:not(:disabled) { filter:brightness(1.1); transform:translateY(-1px); box-shadow:0 6px 20px rgba(0,0,0,0.2); }
        .act-btn:active:not(:disabled) { transform:translateY(0); }
      `}</style>

      <div style={{ maxWidth: 1140, margin: '0 auto', padding: '24px 20px' }}>

        {/* Header */}
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
            <a href="/" style={{ display: 'inline-flex', alignItems: 'center', gap: 6, color: 'var(--text-muted)', textDecoration: 'none', fontSize: 13, padding: '6px 10px', borderRadius: 7, border: '1px solid var(--border)', background: 'var(--surface)' }}>
              ← CRM
            </a>
            <span style={{ color: 'var(--border-strong)' }}>/</span>
            <span style={{ fontWeight: 700, fontSize: 17, color: 'var(--text)' }}>📣 Social Media</span>
          </div>
          <div style={{ display: 'flex', gap: 2, background: 'var(--surface)', borderRadius: 9, padding: 3, border: '1px solid var(--border)' }}>
            {[{ key: 'create', label: '✏️ Criar Post' }, { key: 'schedule', label: '📅 Agendados' }].map(t => (
              <button key={t.key} onClick={() => setTab(t.key as any)}
                style={{ background: tab === t.key ? 'var(--primary)' : 'transparent', color: tab === t.key ? '#fff' : 'var(--text-muted)', border: 'none', borderRadius: 7, padding: '7px 16px', cursor: 'pointer', fontWeight: tab === t.key ? 600 : 400, fontSize: 13, transition: 'all 0.15s' }}>
                {t.label}
              </button>
            ))}
          </div>
        </div>

        {tab === 'create' && (
          <div style={{ display: 'grid', gridTemplateColumns: '300px 1fr', gap: 20, alignItems: 'start' }}>

            {/* ── Coluna esquerda: configurações ── */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>

              {/* Plataforma */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 16, border: '1px solid var(--border)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Plataforma</div>
                <div style={{ display: 'flex', gap: 8 }}>
                  {PLATFORMS.map(p => (
                    <button key={p.value} onClick={() => setPlatform(p.value)} className="act-btn"
                      style={{ flex: 1, background: platform === p.value ? p.color : 'var(--surface-2)', color: platform === p.value ? '#fff' : 'var(--text-secondary)', border: `1px solid ${platform === p.value ? p.color : 'var(--border)'}`, borderRadius: 8, padding: '9px 0', cursor: 'pointer', fontWeight: 600, fontSize: 13, boxShadow: platform === p.value ? `0 2px 10px ${p.color}50` : 'none' }}>
                      {p.icon} {p.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Tema */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 16, border: '1px solid var(--border)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Tema do Post</div>
                <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
                  {TOPICS.map(t => (
                    <button key={t.value} onClick={() => setTopic(t.value)} className="topic-btn"
                      style={{ background: topic === t.value ? 'var(--primary-soft)' : 'transparent', color: topic === t.value ? 'var(--primary)' : 'var(--text-secondary)', border: `1px solid ${topic === t.value ? 'var(--primary-border)' : 'transparent'}`, borderRadius: 7, padding: '7px 10px', cursor: 'pointer', fontSize: 13, textAlign: 'left', fontWeight: topic === t.value ? 600 : 400, transition: 'all 0.12s' }}>
                      {t.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Tom */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 16, border: '1px solid var(--border)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 10 }}>Tom do Post</div>
                <div style={{ display: 'flex', gap: 6 }}>
                  {STYLES.map(s => (
                    <button key={s.value} onClick={() => setStyle(s.value)} className="act-btn"
                      style={{ flex: 1, background: style === s.value ? 'var(--primary)' : 'var(--surface-2)', color: style === s.value ? '#fff' : 'var(--text-secondary)', border: `1px solid ${style === s.value ? 'var(--primary)' : 'var(--border)'}`, borderRadius: 7, padding: '7px 0', cursor: 'pointer', fontSize: 12, fontWeight: style === s.value ? 600 : 400, transition: 'all 0.15s' }}>
                      {s.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* Instrução adicional */}
              <div style={{ background: 'var(--surface)', borderRadius: 12, padding: 16, border: '1px solid var(--border)' }}>
                <div style={{ fontSize: 11, fontWeight: 600, color: 'var(--text-muted)', textTransform: 'uppercase', letterSpacing: '0.06em', marginBottom: 8 }}>Instrução Adicional</div>
                <textarea value={customPrompt} onChange={e => setCustomPrompt(e.target.value)}
                  placeholder="Ex: Mencione integração com TOTVS, foque em distribuidoras de alimentos..."
                  rows={3}
                  style={{ width: '100%', border: '1px solid var(--border-strong)', borderRadius: 8, padding: '8px 10px', fontSize: 12, resize: 'none', boxSizing: 'border-box', fontFamily: 'inherit', color: 'var(--text)', background: 'var(--surface)', outline: 'none', lineHeight: 1.5 }} />
              </div>

              {/* Botão principal */}
              <button onClick={() => generateBoth()} disabled={isLoading} className="act-btn"
                style={{ width: '100%', background: isLoading ? '#94a3b8' : 'linear-gradient(135deg, #2563eb 0%, #7c3aed 100%)', color: '#fff', border: 'none', borderRadius: 10, padding: '14px 0', cursor: isLoading ? 'not-allowed' : 'pointer', fontWeight: 700, fontSize: 14, boxShadow: isLoading ? 'none' : '0 4px 16px rgba(37,99,235,0.4)', letterSpacing: '0.01em' }}>
                {isLoading ? '⏳ Gerando folder com IA...' : '✨ Gerar Folder Completo com IA'}
              </button>

              {/* Botão de upload */}
              <label className="act-btn" style={{ width: '100%', background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 10, padding: '10px 0', cursor: 'pointer', fontWeight: 500, fontSize: 13, textAlign: 'center', display: 'block', color: 'var(--text-secondary)', boxSizing: 'border-box' }}>
                📁 Usar minha própria imagem
                <input type="file" accept="image/*" style={{ display: 'none' }} onChange={e => {
                  const file = e.target.files?.[0];
                  if (file) {
                    const reader = new FileReader();
                    reader.onload = ev => setUploadedImage(ev.target?.result as string);
                    reader.readAsDataURL(file);
                  }
                }} />
              </label>
            </div>

            {/* ── Coluna direita: folder preview + legenda ── */}
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>

              {/* Canvas folder — PREVIEW GRANDE */}
              <div style={{ background: 'var(--surface)', borderRadius: 14, overflow: 'hidden', border: '1px solid var(--border)', boxShadow: '0 4px 20px rgba(0,0,0,0.08)' }}>
                {/* Barra superior do card */}
                <div style={{ padding: '12px 18px', borderBottom: '1px solid var(--border)', display: 'flex', alignItems: 'center', justifyContent: 'space-between', background: 'var(--surface-2)' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <div style={{ width: 28, height: 28, borderRadius: 6, background: platform === 'linkedin' ? '#0a66c2' : 'linear-gradient(135deg,#e1306c,#833ab4)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 14 }}>
                      {platform === 'linkedin' ? '💼' : '📸'}
                    </div>
                    <span style={{ fontWeight: 600, fontSize: 13, color: 'var(--text)' }}>
                      {platform === 'linkedin' ? 'LinkedIn' : 'Instagram'} — Folder Preview
                    </span>
                    {folderReady && <span style={{ fontSize: 11, background: '#dcfce7', color: '#16a34a', borderRadius: 20, padding: '2px 8px', fontWeight: 600 }}>✓ Pronto</span>}
                    {isLoading && <span style={{ fontSize: 11, background: '#fef3c7', color: '#d97706', borderRadius: 20, padding: '2px 8px', fontWeight: 600 }}>⏳ Gerando...</span>}
                  </div>
                  <div style={{ display: 'flex', gap: 6 }}>
                    <button onClick={() => generateImage()} disabled={generatingImage} className="act-btn"
                      style={{ background: 'var(--surface)', border: '1px solid var(--border)', borderRadius: 7, padding: '5px 12px', fontSize: 12, fontWeight: 500, cursor: generatingImage ? 'not-allowed' : 'pointer', color: 'var(--text-secondary)' }}>
                      {generatingImage ? '⏳' : '🔄'} Nova imagem
                    </button>
                    {folderReady && (
                      <button onClick={downloadFolder} className="act-btn"
                        style={{ background: '#16a34a', color: '#fff', border: 'none', borderRadius: 7, padding: '5px 14px', fontSize: 12, fontWeight: 600, cursor: 'pointer', boxShadow: '0 2px 8px rgba(22,163,74,0.3)' }}>
                        ⬇️ Baixar Folder
                      </button>
                    )}
                    {finalImage && (
                      <button onClick={() => { setImageUrl(''); setUploadedImage(''); setFolderReady(false); }} className="act-btn"
                        style={{ background: 'var(--danger-soft)', border: '1px solid #fecaca', borderRadius: 7, padding: '5px 10px', fontSize: 12, cursor: 'pointer', color: 'var(--danger)' }}>
                        🗑️
                      </button>
                    )}
                  </div>
                </div>

                {/* Canvas — folder visual */}
                <div style={{ position: 'relative', width: '100%', background: '#0f172a', minHeight: 320 }}>
                  {(generatingImage || (!folderReady && isLoading)) && (
                    <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 12, zIndex: 2, background: 'rgba(15,23,42,0.85)' }}>
                      <div style={{ fontSize: 36, animation: 'pulse 1.5s infinite' }}>🎨</div>
                      <div style={{ fontSize: 14, color: '#94a3b8', fontWeight: 500 }}>Criando folder visual...</div>
                      <div style={{ width: 200, height: 3, background: '#1e293b', borderRadius: 4, overflow: 'hidden' }}>
                        <div style={{ height: '100%', background: 'linear-gradient(90deg,#2563eb,#7c3aed)', borderRadius: 4, animation: 'shimmer 1.5s infinite', backgroundSize: '200% 100%' }} />
                      </div>
                    </div>
                  )}
                  <canvas ref={canvasRef}
                    style={{ width: '100%', height: 'auto', display: 'block', maxHeight: 520, objectFit: 'contain' }} />
                  {!finalImage && !isLoading && (
                    <div style={{ position: 'absolute', inset: 0, display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: 10, color: '#475569' }}>
                      <div style={{ fontSize: 48 }}>🎨</div>
                      <div style={{ fontSize: 14, fontWeight: 500 }}>Clique em "Gerar Folder Completo com IA"</div>
                      <div style={{ fontSize: 12, color: '#64748b' }}>A IA vai criar um folder profissional pronto para publicar</div>
                    </div>
                  )}
                </div>
              </div>

              {/* Legenda do post */}
              <div style={{ background: 'var(--surface)', borderRadius: 14, border: '1px solid var(--border)', boxShadow: '0 2px 8px rgba(0,0,0,0.05)', overflow: 'hidden' }}>
                <div style={{ padding: '13px 18px', borderBottom: '1px solid var(--border)', background: 'var(--surface-2)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                  <span style={{ fontWeight: 600, fontSize: 13, color: 'var(--text)' }}>📝 Legenda do Post</span>
                  <div style={{ display: 'flex', gap: 6, alignItems: 'center' }}>
                    <span style={{ fontSize: 11, color: 'var(--text-muted)' }}>{caption.length} caracteres</span>
                    <button onClick={() => generateCaption()} disabled={generatingCaption} className="act-btn"
                      style={{ background: 'var(--primary-soft)', border: '1px solid var(--primary-border)', borderRadius: 6, padding: '4px 11px', fontSize: 12, fontWeight: 600, cursor: generatingCaption ? 'not-allowed' : 'pointer', color: 'var(--primary)' }}>
                      {generatingCaption ? '⏳' : '🤖'} Regerar
                    </button>
                  </div>
                </div>
                <div style={{ padding: '14px 18px' }}>
                  {generatingCaption ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                      {[100, 85, 90, 70, 95, 60, 80].map((w, i) => (
                        <div key={i} className="skeleton" style={{ height: 13, width: `${w}%` }} />
                      ))}
                    </div>
                  ) : (
                    <textarea value={caption} onChange={e => setCaption(e.target.value)}
                      placeholder="Clique em 'Gerar Folder Completo com IA' para criar um post profissional..."
                      rows={9}
                      style={{ width: '100%', border: 'none', padding: 0, fontSize: 13, resize: 'none', boxSizing: 'border-box', fontFamily: 'inherit', color: 'var(--text)', background: 'transparent', outline: 'none', lineHeight: 1.7 }} />
                  )}
                </div>
              </div>

              {/* Botões de publicação */}
              <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr 1fr', gap: 10 }}>
                <button onClick={openLinkedIn} disabled={!caption.trim()} className="act-btn"
                  style={{ background: '#0a66c2', color: '#fff', border: 'none', borderRadius: 10, padding: '13px 0', cursor: caption.trim() ? 'pointer' : 'not-allowed', fontWeight: 700, fontSize: 13, opacity: caption.trim() ? 1 : 0.45, boxShadow: caption.trim() ? '0 3px 12px rgba(10,102,194,0.35)' : 'none' }}>
                  💼 LinkedIn
                </button>
                <button onClick={postToInstagram} disabled={posting || !caption.trim()} className="act-btn"
                  style={{ background: 'linear-gradient(135deg,#e1306c,#833ab4)', color: '#fff', border: 'none', borderRadius: 10, padding: '13px 0', cursor: (posting || !caption.trim()) ? 'not-allowed' : 'pointer', fontWeight: 700, fontSize: 13, opacity: (posting || !caption.trim()) ? 0.45 : 1, boxShadow: (!posting && caption.trim()) ? '0 3px 12px rgba(225,48,108,0.35)' : 'none' }}>
                  {posting ? '⏳...' : '📸 Instagram'}
                </button>
                <button onClick={copyCaption} disabled={!caption.trim()} className="act-btn"
                  style={{ background: copied ? '#dcfce7' : 'var(--surface)', color: copied ? '#16a34a' : 'var(--text-secondary)', border: `1px solid ${copied ? '#a7f3d0' : 'var(--border)'}`, borderRadius: 10, padding: '13px 0', cursor: caption.trim() ? 'pointer' : 'not-allowed', fontWeight: 600, fontSize: 13, opacity: caption.trim() ? 1 : 0.45 }}>
                  {copied ? '✅ Copiado!' : '📋 Copiar'}
                </button>
              </div>
            </div>
          </div>
        )}

        {tab === 'schedule' && (
          <div style={{ background: 'var(--surface)', borderRadius: 14, padding: 60, border: '1px solid var(--border)', textAlign: 'center', color: 'var(--text-muted)' }}>
            <div style={{ fontSize: 48, marginBottom: 14 }}>📅</div>
            <div style={{ fontWeight: 700, fontSize: 16, marginBottom: 8, color: 'var(--text)' }}>Agendamento de Posts</div>
            <div style={{ fontSize: 14, color: 'var(--text-secondary)' }}>Em breve: agende posts para LinkedIn e Instagram com antecedência.</div>
          </div>
        )}
      </div>
    </div>
  );
}
